from datetime import datetime
from zoneinfo import ZoneInfo

from backend.app.database import initialize_database, list_draft_study_sessions, replace_draft_study_sessions, update_study_session_statuses
from backend.app.main import apply_scheduled_session_minutes
from backend.app.models import AssignmentInfo, Assignments, DraftStudySession


TZ = ZoneInfo("America/Chicago")


def session(session_id="draft-a-1"):
    return DraftStudySession(
        id=session_id,
        assignment_id="assignment-1",
        course_id="course-1",
        assignment_title="Essay draft",
        start_at=datetime(2026, 7, 30, 16, 0, tzinfo=TZ),
        end_at=datetime(2026, 7, 30, 17, 0, tzinfo=TZ),
        duration_minutes=60,
        sequence_number=1,
        total_assignment_sessions=1,
        placement_reasons=["Generated by CatchUp scheduler."],
    )


def test_draft_study_sessions_persist_across_connections(tmp_path):
    path = tmp_path / "catchup.sqlite3"
    initialize_database(path)

    replace_draft_study_sessions("user-1", [session()], path)
    loaded = list_draft_study_sessions("user-1", path)

    assert len(loaded) == 1
    assert loaded[0].assignment_id == "assignment-1"
    assert loaded[0].start_at == datetime(2026, 7, 30, 16, 0, tzinfo=TZ)


def test_replacing_draft_study_sessions_removes_old_drafts(tmp_path):
    path = tmp_path / "catchup.sqlite3"
    initialize_database(path)

    replace_draft_study_sessions("user-1", [session("old")], path)
    replace_draft_study_sessions("user-1", [session("new")], path)
    loaded = list_draft_study_sessions("user-1", path)

    assert [item.id for item in loaded] == ["new"]


def test_approving_sessions_reports_success_and_failures(tmp_path):
    path = tmp_path / "catchup.sqlite3"
    initialize_database(path)
    replace_draft_study_sessions("user-1", [session("saved")], path)

    sessions, approved_ids, failed_ids = update_study_session_statuses(
        "user-1",
        ["saved", "missing"],
        "approved",
        path,
    )

    assert approved_ids == ["saved"]
    assert failed_ids == ["missing"]
    assert sessions[0].status == "approved"


def test_persisted_draft_minutes_attach_to_assignment_progress():
    assignments = Assignments(assignments=[
        AssignmentInfo(
            assignment_id="assignment-1",
            course_id="course-1",
            title="Essay draft",
            estimated_minutes=90,
        )
    ])

    updated = apply_scheduled_session_minutes(assignments, [session()])

    assert updated.assignments[0].scheduled_minutes == 60
