import type { Assignment, CalendarEvent, Course, SchedulingFailure, StudySession } from "../types";

export interface BackendClassInfo {
  name: string;
  course_id: string;
  subject?: string | null;
  description?: string | null;
  teachers: string[];
}

export interface BackendAssignmentInfo {
  title: string;
  description?: string | null;
  due_date?: string | null;
  due_time?: string | null;
  estimated_minutes?: number | null;
  course_id: string;
  assignment_id: string;
  submission_state?: string | null;
}

export interface BackendPriorityLevel {
  level: "low" | "medium" | "high";
  score: number;
  reasons: string[];
}

export interface BackendCalendarEvent {
  id?: string | null;
  title: string;
  user_id: string;
  start_time: string;
  end_time: string;
  description?: string | null;
}

export interface BackendStudyEvent {
  id?: string | null;
  title: string;
  user_id: string;
  assignment_id: string;
  start_time: string;
  end_time: string;
  description?: string | null;
  status: "draft" | "approved" | "synced" | "conflict";
  google_calendar_event_id?: string | null;
}

export interface BackendSchedulingFailure {
  assignment_id: string;
  title: string;
  reason: string;
}

export function adaptCourse(item: BackendClassInfo): Course {
  return {
    id: item.course_id,
    name: item.name,
    teacher: item.teachers[0] ?? "Unknown teacher",
    section: item.subject ?? "Active course",
    subject: item.subject ?? undefined,
    description: item.description ?? undefined,
    activeAssignmentCount: 0,
    tracked: true,
    color: "#0F766E",
    initials: item.name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase(),
  };
}

export function adaptAssignment(item: BackendAssignmentInfo, priority: BackendPriorityLevel, courseName = "Class"): Assignment {
  const dueAt = item.due_date ? `${item.due_date}T${item.due_time ?? "23:59:00"}` : null;
  return {
    id: item.assignment_id,
    classroomId: item.assignment_id,
    courseId: item.course_id,
    courseName,
    title: item.title,
    description: item.description ?? "",
    dueAt,
    dueLabel: dueAt ? new Date(dueAt).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "No due date",
    dueShort: dueAt ? new Date(dueAt).toLocaleDateString([], { weekday: "short" }) : "Backlog",
    estimatedMinutes: item.estimated_minutes ?? 30,
    priority: priority.level,
    priorityScore: priority.score,
    status: dueAt ? "Unscheduled" : "Backlog",
    submissionState: item.submission_state ?? "Assigned",
    source: "google-classroom",
    overdue: dueAt ? new Date(dueAt) < new Date() : false,
    noDueDate: !dueAt,
    color: "#0F766E",
    priorityExplanation: {
      assignmentId: item.assignment_id,
      score: priority.score,
      level: priority.level,
      reasons: priority.reasons,
    },
  };
}

export function adaptCalendarEvent(item: BackendCalendarEvent): CalendarEvent {
  return {
    id: item.id ?? item.title,
    title: item.title,
    source: "google-calendar",
    readonly: true,
    startAt: item.start_time,
    endAt: item.end_time,
    description: item.description ?? undefined,
  };
}

export function adaptStudyEvent(item: BackendStudyEvent): StudySession {
  const start = new Date(item.start_time);
  const end = new Date(item.end_time);
  return {
    id: item.id ?? `${item.assignment_id}-${item.start_time}`,
    title: item.title.replace(/^Study:\s*/, ""),
    assignmentId: item.assignment_id,
    courseId: "",
    source: "catchup",
    status: item.status,
    startAt: item.start_time,
    endAt: item.end_time,
    durationMinutes: Math.round((end.getTime() - start.getTime()) / 60000),
    reason: "Generated by CatchUp scheduler",
    googleCalendarEventId: item.google_calendar_event_id ?? undefined,
  };
}

export function adaptSchedulingFailure(item: BackendSchedulingFailure): SchedulingFailure {
  return {
    assignmentId: item.assignment_id,
    title: item.title,
    reason: item.reason,
  };
}
