import type { AppContextValue } from "../App";
import type { UserPreferences } from "../types";

export function SettingsPage({ app }: { app: AppContextValue }) {
  const preferences = app.data.preferences;
  function update(patch: Partial<UserPreferences>) {
    app.updatePreferences({ ...preferences, ...patch });
  }

  return (
    <main className="main">
      <div className="page-heading"><div><h2>Settings</h2><p>Control integrations, study availability, and how CatchUp creates draft plans.</p></div><div className="heading-actions"><button className="btn btn-primary" onClick={() => app.toast("Preferences saved.")}>Save changes</button></div></div>
      <div className="settings-layout"><aside className="card settings-nav"><button className="active">Study preferences</button><button>Integrations</button><button>Tracked classes</button><button>Calendar</button><button>Notifications</button><button>Data & privacy</button></aside><div>
        <section className="card settings-card"><h3>Study availability</h3><p>CatchUp searches for free time only within these hours.</p><div className="setting-row"><div className="setting-copy"><strong>School-night study window</strong><span>Monday through Friday</span></div><div className="field"><input type="time" value={preferences.schoolNightStart} onChange={(event) => update({ schoolNightStart: event.target.value })} /><span>to</span><input type="time" value={preferences.schoolNightEnd} onChange={(event) => update({ schoolNightEnd: event.target.value })} /></div></div><div className="setting-row"><div className="setting-copy"><strong>Include weekends</strong><span>Allow plans on Saturday and Sunday.</span></div><label className="switch"><input type="checkbox" checked={preferences.includeWeekends} onChange={(event) => update({ includeWeekends: event.target.checked })} /><span className="slider" /></label></div><div className="setting-row"><div className="setting-copy"><strong>Maximum school-night workload</strong><span>Protect against unrealistic plans.</span></div><select className="select" value={preferences.maxSchoolNightMinutes} onChange={(event) => update({ maxSchoolNightMinutes: Number(event.target.value) })}><option value={120}>2 hours</option><option value={60}>1 hour</option><option value={180}>3 hours</option></select></div></section>
        <section className="card settings-card"><h3>Study sessions</h3><p>These defaults can still be changed during plan review.</p><div className="setting-row"><div className="setting-copy"><strong>Maximum session length</strong><span>Long assignments can be split automatically.</span></div><select className="select" value={preferences.maxSessionMinutes} onChange={(event) => update({ maxSessionMinutes: Number(event.target.value) })}><option value={60}>60 minutes</option><option value={45}>45 minutes</option><option value={90}>90 minutes</option></select></div><div className="setting-row"><div className="setting-copy"><strong>Minimum break</strong><span>Time between CatchUp study blocks.</span></div><select className="select" value={preferences.minBreakMinutes} onChange={(event) => update({ minBreakMinutes: Number(event.target.value) })}><option value={10}>10 minutes</option><option value={15}>15 minutes</option><option value={0}>No minimum</option></select></div><div className="setting-row"><div className="setting-copy"><strong>Schedule overdue work ASAP</strong><span>Use the earliest suitable opening.</span></div><label className="switch"><input type="checkbox" checked={preferences.scheduleOverdueAsap} onChange={(event) => update({ scheduleOverdueAsap: event.target.checked })} /><span className="slider" /></label></div></section>
        <section className="card settings-card"><h3>Google connections</h3><p>CatchUp never adds Calendar events without review.</p><div className="setting-row"><div className="setting-copy"><strong>Google Classroom</strong><span>Connected as chinmay@example.com</span></div><span className="badge badge-success">Connected</span></div><div className="setting-row"><div className="setting-copy"><strong>Google Calendar</strong><span>Reading commitments and adding approved sessions</span></div><span className="badge badge-success">Connected</span></div></section>
      </div></div>
    </main>
  );
}
